### ISSUE TITLE
Rename "browser" to "sanelenium instance" 

### ISSUE THREAD

**Issue by kevgo** [Originate/nifty#5]
Currently it uses "browser" for two separate concepts: 
* the Sanelenium instance
* the user's actual browser that is remote-controlled by the Sanelenium instance

This is confusing. I propose to rename the `Browser` class to `Sanelenium`, so that it is used like

```coffeescript
sanelenium = new Sanelenium 'http://localhost:5000'
sanelenium.$('foo').click()
```

**Comment by alexdavid** [comment]
Renamed it to niftyBrowser. It's accessible through `Nifty.Browser`  I think this is a good compromise.
